spring:
  application:
    name: id-gen
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/id_gen?useSSL=false
    username: ares
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
snd:
  rate-limiter:
    enabled: true
