spring:
  application:
    name: id-gen
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/id_gen?useSSL=false
    username: root
    password: xp1234$#@!
    driver-class-name: com.mysql.cj.jdbc.Driver
